name: Creative Code Graz
url: http://creativecode.at/

#### Under the Hood Stuff #####
permalink: pretty
markdown: kramdown
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, node_modules]
